### ISSUE TITLE
Question regarding commission rates

### ISSUE THREAD

**Issue by brandon-a-hay** [JDutil/spree_marketplace#14]
Hi Jeff,

This isn't really an issue I just didn't see any other place to contact you. I just wanted to clarify what the setting for commission rates mean for the suppliers. I assume that it means that the Stripe account owner will take x percentage from the transactions on those suppliers right? So if I wanted to take a 10% cut from all of Spree transactions I would need to specify that in the settings for each supplier?

Thanks!

**Comment by JDutil** [comment]
Yes or you can set the default for all suppliers to 10% so that they each get set to 10% without doing it for each individual one.

**Comment by brandon-a-hay** [comment]
Hey Jeff,

Question: I've set the commission up for these suppliers and had them setup
their bank accounts, yet the entire value of the Spree transactions is
going to my bank account associated with my Stripe account. Am I missing a
configuration setting or something? Do I need to enable something in my
Stripe account to allow it to push the 90% of the transaction to their
specific accounts? I only want to skim the 10% off the top.

Thanks for your support

**Comment by brandon-a-hay** [comment]
To add on to that, I have a list of transfer recipients in my Stripe
dashboard, but none of them have their bank account information loaded in
there. Should your gem be automatically populating that data when the new
suppliers enter that into the form on Spree?

**Comment by JDutil** [comment]
I never finished programming the payout that's something still in the todo list https://github.com/JDutil/spree_marketplace#todo that you'll have to do yourself as I'm no longer developing this extension.

**Comment by brandon-a-hay** [comment]
Alright thanks for letting me know.

**Comment by brandon-a-hay** [comment]
Can you point me in the right direction? I get that the bank information
needs to be passed to the POST request via the Stripe API. Do you know what
file/s I'll need to change to have that updated?
